local colour = require("colour")

return {
	Added = { fg = colour.olive, bold = true },
	Boolean = { fg = colour.mauve },
	Changed = { link = "Type" },
	Character = { link = "Boolean" },
	ColorColumn = { link = "NonText" },
	Command = { fg = colour.slate, bold = true },
	Comment = { fg = colour.raven, italic = true },
	Conceal = { link = "Comment" },
	Conditional = { link = "Character" },
	Constant = { link = "Macro" },
	CurSearch = { fg = colour.ultra, bg = colour.mauve },
	Cursor = { fg = colour.pearl, bg = colour.coola },
	CursorLine = { bg = colour.depth },
	CursorLineNr = { fg = colour.coola, bold = true },
	Debug = { link = "Boolean" },
	Define = { link = "Macro" },
	Delimiter = { link = "LineNr" },
	DiagnositicSignInfo = { bg = colour.raven },
	DiagnosticError = { link = "Error" },
	DiagnosticHint = { link = "Boolean" },
	DiagnosticInfo = { link = "Changed" },
	DiagnosticInformation = { link = "Changed" },
	DiagnosticUnderlineError = { fg = colour.blush, undercurl = true },
	DiagnosticUnderlineHint = { fg = colour.paris, undercurl = true },
	DiagnosticUnderlineInfo = { fg = colour.metal, undercurl = true },
	DiagnosticUnderlineWarn = { fg = colour.amber, undercurl = true },
	DiagnosticUnnecessary = { fg = colour.raven, undercurl = true },
	DiagnosticVirtualTextError = { fg = colour.blush, bg = colour.rouge },
	DiagnosticVirtualTextHint = { fg = colour.paris, bg = colour.bazil },
	DiagnosticVirtualTextInfo = { fg = colour.capri, bg = colour.raven },
	DiagnosticVirtualTextWarn = { fg = colour.peach, bg = colour.amber },
	DiagnosticWarn = { link = "Tag" },
	DiagnosticWarning = { link = "DiagnosticWarn" },
	DiffChange = { link = "LineNr" },
	Directory = { fg = colour.steel, bold = true },
	EndOfBuffer = { link = "StatusLineNC" },
	Error = { fg = colour.blush },
	ErrorMsg = { link = "Error" },
	Exception = { link = "Macro" },
	Field = { link = "Normal" },
	Float = { link = "Boolean" },
	FloatBorder = { fg = colour.depth, bg = "NONE" },
	FloatShadow = { link = "NonText" },
	FloatShadowThrough = { link = "NonText" },
	FoldColumn = { link = "FloatBorder" },
	Folded = { link = "LineNr" },
	Function = { fg = colour.metal, bold = true },
	Identifier = { link = "Normal" },
	Ignore = { fg = colour.ultra },
	IncSearch = { link = "String" },
	Include = { link = "Macro" },
	Italic = { italic = true },
	KeywordFunction = { link = "Macro" },
	KeywordReturn = { link = "Return" },
	Label = { link = "Macro" },
	LazyGitBorder = { link = "FloatBorder" },
	LazyGitFloat = { link = "Type" },
	LineNr = { fg = colour.raven },
	Macro = { fg = colour.metal },
	MatchParen = { fg = colour.blush, bold = true },
	Menu = { fg = colour.metal, bg = colour.depth },
	Noise = { link = "Boolean" },
	NonText = { fg = "NONE", bg = "NONE" },
	Normal = { fg = colour.pearl },
	NormalFloat = { link = "Pmenu" },
	Number = { link = "Boolean" },
	NvimInternalError = { link = "Error" },
	Operator = { link = "LineNr" },
	Pmenu = { fg = colour.ghost, bg = "NONE" },
	PmenuSbar = { fg = colour.raven, bg = colour.depth },
	PmenuSel = { fg = colour.slate, bg = colour.raven },
	PmenuThumb = { fg = colour.raven, bg = colour.depth },
	PreProc = { link = "Type" },
	Quote = { link = "Macro" },
	Removed = { fg = colour.rouge },
	Repeat = { link = "Macro" },
	Return = { fg = colour.bazil, bold = true },
	Search = { fg = colour.capri, bg = colour.steel, bold = true },
	SignColumn = { link = "LineNr" },
	Special = { link = "Macro" },
	SpecialChar = { link = "Boolean" },
	SpecialComment = { link = "Comment" },
	SpecialKey = { link = "Macro" },
	SpellBad = { link = "Boolean" },
	SpellCap = { link = "LineNr" },
	Statement = { link = "Return" },
	StatusLine = { bg = colour.depth },
	StatusLineNC = { fg = colour.space, bg = "NONE" },
	String = { fg = colour.paris },
	Tag = { fg = colour.amber },
	TargetWord = { fg = colour.capri },
	Title = { link = "Normal" },
	Todo = { fg = colour.royal, bold = true },
	Type = { fg = colour.slate },
	Visual = { bg = colour.coola, fg = colour.ultra },
	WarningMsg = { link = "Tag", italic = true },
	Whitespace = { fg = colour.space },
	WildMenu = { link = "MatchParen" },
	WinBar = { link = "LineNr" },
	WinBarNC = { link = "LineNr" },
	WinSeparator = { fg = colour.steel },
	["@comment.documentation"] = { link = "Comment" },
	["@comment.error"] = { link = "Error" },
	["@comment.note"] = { link = "Return" },
	["@comment.todo"] = { link = "Todo" },
	["@comment.warning"] = { link = "Tag" },
	["@constructor.lua"] = { link = "LineNr" },
	["@function.lua"] = { link = "Command" },
	["@keyword.conditional.lua"] = { link = "Boolean" },
	["@keyword.function.lua"] = { link = "Macro" },
	["@keyword.lua"] = { link = "Added" },
	["@keyword.repeat.lua"] = { link = "Added" },
	["@keyword.return.lua"] = { link = "Return" },
	["@operator.lua"] = { link = "LineNr" },
	["@variable"] = { link = "Normal" },
	["@variable.lua"] = { link = "Normal" },
	constructor = { fg = colour.steel, italic = true },
	cssAttrRegion = { link = "Todo" },
	cssBraces = { link = "LineNr" },
	cssClassName = { link = "Macro" },
	cssClassNameDot = { link = "Boolean" },
	cssDefinition = { link = "Changed" },
	cssNoise = { link = "LineNr" },
	cssPositioningAttr = { link = "@keyword.lua" },
	cssPseudoClassId = { link = "Added" },
	cssTagName = { link = "Boolean" },
	htmlTag = { link = "LineNr" },
	htmlTagName = { link = "Macro" },
	keyword = { fg = colour.olive, bold = true },
	markdownCodeBlock = { fg = colour.olive },
	markdownH1 = { link = "LineNr" },
	markdownH2 = { link = "LineNr" },
	markdownItalic = { link = "String" },
	markdownRule = { link = "LineNr" },
	muttrcCommand = { link = "Macro" },
	shDerefSimple = { fg = colour.royal },
	shQuote = { link = "String" },
	tmuxCommands = { link = "Macro" },
	tmuxFlags = { link = "Boolean" },
	tmuxFormatString = { link = "Todo" },
	tmuxOptions = { link = "Normal" },
	tmuxString = { link = "String" },
	tmuxVariableExpansion = { fg = colour.royal },
	tsxAttrib = { fg = colour.capri },
	tsxCloseComponentName = { link = "Keyword" },
	tsxCloseString = { link = "tsxTag" },
	tsxCloseTag = { link = "tsxTag" },
	tsxCloseTagName = { link = "tsxTag" },
	tsxEqual = { link = "LineNr" },
	tsxIntrinsicTagName = { link = "tsxTag" },
	tsxJsBlock = { link = "Normal" },
	tsxRegion = { link = "Normal" },
	tsxString = { link = "String" },
	tsxTag = { fg = colour.steel, bold = true },
	tsxTagName = { fg = colour.steel, bold = true },
	typescriptAliasKeyword = { link = "Macro" },
	typescriptArray = { link = "Normal" },
	typescriptArrayMethod = { link = "Macro" },
	typescriptArrowFunc = { link = "LineNr" },
	typescriptArrowFuncArg = { link = "Normal" },
	typescriptArrowFuncDef = { link = "Comment" },
	typescriptAssign = { link = "LineNr" },
	typescriptAsyncFuncKeyword = { link = "Character" },
	typescriptBOMHistoryProp = { link = "Boolean" },
	typescriptBinaryOp = { link = "Number" },
	typescriptBlock = { link = "Normal" },
	typescriptBraces = { link = "LineNr" },
	typescriptCall = { link = "Type" },
	typescriptConditional = { link = "Boolean" },
	typescriptDOMDocMethod = { link = "Type" },
	typescriptDOMDocProp = { link = "Type" },
	typescriptDefault = { link = "Return" },
	typescriptDotNotation = { link = "Boolean" },
	typescriptExceptions = { link = "typescriptTry" },
	typescriptFuncCallArg = { link = "Type" },
	typescriptFuncKeyword = { link = "Macro" },
	typescriptFuncName = { fg = colour.slate, bold = true },
	typescriptGlobal = { fg = colour.capri },
	typescriptIdentifierName = { link = "Macro" },
	typescriptMember = { link = "Normal" },
	typescriptMemberOptionality = { link = "Boolean" },
	typescriptObjectColon = { link = "LineNr" },
	typescriptObjectLabel = { link = "TargetWord" },
	typescriptObjectLiteral = { link = "Boolean" },
	typescriptObjectSpread = { link = "Boolean" },
	typescriptOperator = { link = "Added" },
	typescriptParenExp = { link = "tsxTag" },
	typescriptParens = { link = "LineNr" },
	typescriptPredefinedType = { link = "String" },
	typescriptProp = { link = "Boolean" },
	typescriptProperty = { link = "Boolean" },
	typescriptTemplate = { link = "Tag" },
	typescriptTemplateSB = { link = "Tag" },
	typescriptTemplateSubstitution = { link = "Todo" },
	typescriptTernaryOp = { link = "Tag" },
	typescriptTry = { fg = colour.mauve, bold = true, italic = true },
	typescriptTypeAnnotation = { link = "LineNr" },
	typescriptTypeArguments = { fg = colour.steel },
	typescriptTypeBracket = { link = "LineNr" },
	typescriptTypeBrackets = { fg = colour.steel },
	typescriptUnaryOp = { link = "Boolean" },
	typescriptVariable = { link = "Macro" },
	variable = { link = "Normal" },
	vimEnvvar = { link = "Boolean" },
	vimOper = { link = "Boolean" },
	vimOperParen = { link = "LineNr" },
	vimUserFunc = { link = "Normal" },
	vimVar = { link = "TargetWord" },
	zshCommands = { link = "Macro" },
}
