local function highlight(group, styles)
  vim.api.nvim_set_hl(0, group, styles)
end

local colour = {
  space = '#111119',
  raven = '#1E202D',
  metal = '#3B4267',
  steel = '#405080',
  royal = '#6070C1',
  capri = '#7AA7FF',
  ultra = '#CBA6F7',
  mauve = '#734a80',
  rouge = '#A94064',
  peach = '#FFCDCD',
  amber = '#DB9280',
  bazil = '#597a69',
  olive = '#5F875F',
  paris = '#9EBFBF',
  slate = '#676E96',
  pearl = '#9FA7CF'
}

local editor_syntax = {
  Cursor                  = { fg = colour.pearl, bg = colour.rouge },
  CursorLine              = { bg = colour.raven },
  ColorColumn             = { fg = "NONE", bg = "NONE" },
  CursorLineNr            = { fg = colour.capri, bg = colour.raven },
  Directory               = { fg = colour.steel, bold = true },
  variable                = { fg = colour.pearl },
  field                   = { fg = colour.pearl },
  DiffAdd                 = { fg = colour.paris },
  DiffChange              = { fg = colour.metal },
  DiffDelete              = { fg = colour.rouge },
  DiffText                = { fg = colour.royal },
  ErrorMsg                = { fg = colour.rouge },
  EndOfBuffer             = { fg = colour.space, bg = colour.space },
  VertSplit               = { fg = colour.metal, bg = colour.space },
  Folded                  = { fg = colour.mauve, italic = true },
  FoldColumn              = { fg = colour.mauve },
  SignColumn              = { fg = colour.peach },
  IncSearch               = { fg = colour.ultra, bg = colour.royal, bold = true },
  Substitute              = { fg = colour.pearl, bg = colour.rouge },
  LineNr                  = { fg = colour.metal },
  MatchParen              = { fg = colour.rouge, bold = true },
  Normal                  = { fg = colour.pearl, bg = colour.space },
  NormalFloat             = { bg = colour.space },
  Pmenu                   = { fg = colour.pearl, bg = colour.space },
  PmenuSel                = { fg = colour.capri, bg = colour.raven, bold = true },
  PmenuSbar               = { fg = colour.pearl },
  PmenuThumb              = { fg = colour.rouge, bg = colour.rouge },
  TabLine                 = { fg = colour.pearl, bg = colour.rouge },
  TabLineFill             = { fg = colour.pearl, bg = colour.metal },
  TabLineSel              = { fg = colour.space, bg = colour.raven, bold = true },
  Search                  = { fg = colour.pearl, bg = colour.royal },
  SpecialKey              = { fg = colour.royal },
  SpellBad                = { fg = colour.rouge, bold = true },
  SpellRare               = { fg = colour.royal, bold = true },
  SpellCap                = { fg = colour.peach, bold = true },
  SpellLocal              = { fg = colour.amber, bold = true },
  Title                   = { fg = colour.pearl },
  Visual                  = { fg = colour.pearl, bg = colour.royal },
  VisualNOS               = { fg = colour.pearl, bg = colour.rouge },
  WarningMsg              = { fg = colour.peach },
  Whitespace              = { fg = colour.capri },
  FloatBorder             = { fg = colour.raven },
  FloatShadow             = { bg = "NONE" },
  FloatShadowThrough      = { bg = "NONE" },
  constructor             = { fg = colour.pearl, bold = true },
  Builtin                 = { fg = colour.pearl },
  Return                  = { fg = colour.bazil, bold = true },
  gitcommitComment        = { fg = colour.metal },
  gitcommitUntracked      = { fg = colour.metal },
  gitcommitDiscarded      = { fg = colour.metal },
  gitcommitSelected       = { fg = colour.metal },
  gitcommitBranch         = { fg = colour.ultra, bold = true },
  gitcommitNoBranch       = { fg = colour.ultra },
  gitcommitDiscardedType  = { fg = colour.rouge },
  gitcommitDiscardedFile  = { fg = colour.rouge },
  gitcommitDiscardedArrow = { fg = colour.rouge },
  gitcommitOverflow       = { fg = colour.rouge },
  gitcommitUntrackedFile  = { fg = colour.royal },
  gitcommitUnmerged       = { fg = colour.olive },
  gitcommitSelectedFile   = { fg = colour.olive },
  gitcommitSelectedType   = { fg = colour.olive },
  gitcommitSelectedArrow  = { fg = colour.olive },
  gitcommitUnmergedFile   = { fg = colour.peach },
  gitcommitUnmergedArrow  = { fg = colour.peach },
  gitcommitSummary        = { fg = colour.pearl },
  gitcommitOnBranch       = {},
  gitcommitHeader         = {},
  gitcommitFile           = {},
  Conceal                 = {},
  ModeMsg                 = {},
  MsgArea                 = {},
  MsgSeparator            = {},
  MoreMsg                 = {},
  NonText                 = {},
  Question                = {},
  QuickFixLine            = {},
  StatusLine              = {},
  StatusLineNC            = {},
  WildMenu                = {}
}

for group, styles in pairs(editor_syntax) do
  highlight(tostring(group), styles)
end

local code_syntax = {
  Boolean                    = { fg = colour.mauve },
  Character                  = { link = 'constructor' },
  Command                    = { link = 'DiffText' },
  Comment                    = { fg = colour.metal, bold = true, italic = true },
  Conditional                = { fg = colour.royal },
  Constant                   = { link = 'DiffText' },
  Debug                      = { link = 'DiffDelete' },
  Define                     = { link = 'DiffText' },
  Delimiter                  = { link = 'LineNr' },
  Error                      = { link = 'ErrorMsg' },
  Exception                  = { fg = colour.royal, bold = true },
  Function                   = { link = 'constructor' },
  Field                      = { link = 'variable' },
  Float                      = { link = 'gitcommitBranch' },
  Identifier                 = { link = 'variable' },
  Ignore                     = { link = 'DiffChange' },
  Include                    = { fg = colour.royal, bold = true },
  KeywordFunction            = { link = 'DiffText' },
  KeywordReturn              = { fg = colour.olive, italic = true },
  Label                      = { link = 'DiffText' },
  Macro                      = { fg = colour.royal },
  Noise                      = { fg = colour.rouge },
  Number                     = { fg = colour.ultra, bold = true },
  NvimInternalError          = { link = 'ErrorMsg' },
  Operator                   = { fg = colour.peach },
  PreCondit                  = { link = 'DiffChange' },
  PreProc                    = { fg = colour.slate },
  Repeat                     = { link = 'Return' },
  Special                    = { fg = colour.royal },
  SpecialChar                = { link = 'ErrorMsg' },
  SpecialComment             = { fg = colour.metal, bold = true },
  Statement                  = { fg = colour.royal, bold = true },
  StorageClass               = { fg = colour.rouge },
  String                     = { fg = colour.paris, italic = true },
  Structure                  = { fg = colour.pearl },
  Tag                        = { fg = colour.amber },
  TelescopeBorder            = { link = 'FloatBorder' },
  TelescopeSelection         = { link = 'PmenuSel' },
  TelescopeSelectionCaret    = { fg = colour.rouge, bg = colour.raven, bold = true },
  TelescopeMatching          = { fg = colour.ultra, bold = true },
  TelescopePreviewMatch      = { link = 'MatchParen' },
  TelescopePromptTitle       = { fg = colour.royal },
  TelescopePromptPrefix      = { fg = colour.rouge },
  Todo                       = { fg = colour.capri, bold = true },
  Type                       = { fg = colour.paris, bold = true },
  Typedef                    = { link = 'DiffChange' },
  -- Underlined                 = { gui = 'underline' },
  htmlEndTag                 = { link = 'LineNr' },
  htmlTag                    = { link = 'LineNr' },
  htmlHead                   = { link = 'DiffText' },
  htmlTagN                   = { fg = colour.royal, bold = true },
  htmlTagName                = { fg = colour.royal, bold = true },
  htmlSpecialTagName         = { fg = colour.royal },
  htmlArg                    = { link = 'LineNr' },
  keyword                    = { link = 'Directory' },
  DiagnosticWarn             = { fg = colour.amber },
  DiagnosticInfo             = { fg = colour.capri },
  DiagnosticHint             = { fg = colour.peach, bold = true },
  DiagnosticError            = { fg = colour.rouge, bold = true },
  DiagnosticUnderlineError   = { fg = colour.rouge, bold = true },
  DiagnosticVirtualTextError = { fg = colour.rouge, bold = true },
  DiagnosticUnderlineWarn    = { fg = colour.amber },
  DiagnosticUnderlineInfo    = { fg = colour.capri },
  DiagnosticUnderlineHint    = { fg = colour.peach },
  DiagnosticVirtualTextInfo  = { fg = colour.capri },
  DiagnosticVirtualTextWarn  = { fg = colour.amber },
  DiagnosticVirtualTextHint  = { fg = colour.peach },
}

for group, styles in pairs(code_syntax) do
  highlight(tostring(group), styles)
end

--> Plugin Highlight Groups
local plugin_syntax = {
  GitGutterAdd          = { link = 'gitcommitUnmerged' },
  GitGutterChange       = { link = 'LineNr' },
  GitGutterDelete       = { link = 'DiffDelete' },
  GitGutterChangeDelete = { fg = colour.amber },
  diffAdded             = { link = 'gitcommitUnmerged' },
  diffRemoved           = { link = 'DiffDelete' },
  NotifyERRORBorder     = { link = 'ErrorMsg' },
  NotifyWARNBorder      = { link = 'FoldColumn' },
  NotifyINFOBorder      = { fg = colour.bazil },
  NotifyDEBUGBorder     = { fg = colour.slate },
  NotifyTRACEBorder     = { fg = colour.mauve },
  NotifyERRORIcon       = { link = 'DiffDelete' },
  NotifyWARNIcon        = { link = 'Tag' },
  NotifyINFOIcon        = { link = 'DiffAdd' },
  NotifyDEBUGIcon       = { fg = colour.slate },
  NotifyDEBUGTitle      = { fg = colour.slate },
  NotifyTRACEIcon       = { link = 'gitcommitNoBranch' },
  NotifyERRORTitle      = { link = 'DiffDelete' },
  NotifyWARNTitle       = { link = 'Tag' },
  NotifyINFOTitle       = { link = 'DiffAdd' },
  NotifyTRACETitle      = { link = 'gitcommitNoBranch' },
  NotifyERRORBody       = { link = 'Normal' },
  NotifyWARNBody        = { link = 'Normal' },
  NotifyINFOBody        = { link = 'Normal' },
  NotifyDEBUGBody       = { link = 'Normal' },
  NotifyTRACEBody       = { link = 'Normal' },
}

for group, styles in pairs(plugin_syntax) do
  highlight(tostring(group), styles)
end

local lang_syntax = {
  xmlEndTag                      = { fg = colour.royal, bold = true },
  luaBraces                      = { link = 'LineNr' },
  luaBuiltIn                     = { link = 'DiffText' },
  luaComma                       = { link = 'LineNr' },
  luaConstant                    = { link = 'gitcommitBranch' },
  luaFunc                        = { link = 'DiffText' },
  luaFuncArgsComma               = { link = 'LineNr' },
  luaFuncCall                    = { link = 'Directory' },
  mkdNonListItemBlock            = { link = 'Folded' },
  luaFuncName                    = { link = 'constructor' },
  luaFuncParens                  = { link = 'LineNr' },
  luaFunction                    = { fg = colour.royal },
  luaFunctionBlock               = { fg = colour.royal, bold = true },
  luaIn                          = { fg = colour.royal, bold = true },
  luaKeyword                     = { link = 'Return' },
  luaLocal                       = { fg = colour.olive, bold = true },
  luaParen                       = { link = 'LineNr' },
  luaParens                      = { link = 'LineNr' },
  luaSpecialValue                = { link = 'Directory' },
  luaStatement                   = { link = 'Return' },
  luaString                      = { link = 'String' },
  luaStringLongTag               = { fg = colour.metal, bold = true },
  luaSymbolOperator              = { link = 'LineNr' },
  luaTable                       = { link = 'LineNr' },
  luaTableBlock                  = { link = 'LineNr' },
  FidgetTitle                    = { fg = colour.capri, bg = colour.space },
  tmuxFormatString               = { fg = colour.capri },
  tmuxOptions                    = { link = 'variable' },
  tmuxAssignment                 = { link = 'LineNr' },
  tmuxFlags                      = { link = 'ErrorMsg' },
  tmuxVariableExtension          = { fg = colour.amber },
  shDo                           = { link = 'ErrorMsg' },
  shQuote                        = { fg = colour.amber },
  shStatement                    = { link = 'htmlTagN' },
  shTestOpr                      = { link = 'ErrorMsg' },
  shVar                          = { fg = colour.capri },
  shEcho                         = { fg = colour.paris, italic = true },
  shVarAssign                    = { link = 'LineNr' },
  zshCommands                    = { link = 'DiffText' },
  zshFunction                    = { link = 'WarningMsg' },
  zshKeyword                     = { link = 'Function' },
  zshNumber                      = { link = 'Number' },
  zshOptStart                    = { fg = colour.royal, bold = true },
  zshOption                      = { fg = colour.royal, bold = true },
  zshPreProc                     = { link = 'PreProc' },
  zshPrecommand                  = { link = 'DiffText' },
  zshString                      = { link = 'String' },
  zshSubst                       = { link = 'DiffChange' },
  zshSubstDelim                  = { fg = colour.amber },
  zshTodo                        = { link = 'Todo' },
  zslhComment                    = { link = 'Comment' },
  zshStringDelimiter             = { link = 'String' },
  zshParentheses                 = { fg = colour.mauve },
  zshDeref                       = { link = 'Whitespace' },
  shDerefSimple                  = { fg = colour.amber },
  shDoubleQuote                  = { fg = colour.amber },
  rustAssert                     = { link = 'ErrorMsg' },
  rustBoxPlacementBalance        = { link = 'ErrorMsg' },
  rustFoldBraces                 = { link = 'LineNr' },
  rustEnumVariant                = { link = 'field' },
  rustFuncCall                   = { link = 'field' },
  rustRepeat                     = { link = 'Directory' },
  rustKeyword                    = { link = 'Directory' },
  rustConditional                = { link = 'Directory' },
  rustFuncName                   = { link = 'constructor' },
  rustCharacter                  = { link = 'ErrorMsg' },
  rustIdentifier                 = { link = 'variable' },
  rustMacro                      = { link = 'Return' },
  rustModPath                    = { link = 'Return' },
  rustModPathSep                 = { link = 'LineNr' },
  rustOperator                   = { link = 'LineNr' },
  rustSelf                       = { link = 'ErrorMsg' },
  rustSigil                      = { link = 'ErrorMsg' },
  rustStorage                    = { link = 'Directory' },
  rustStructure                  = { link = 'Return' },
  rustTrait                      = { link = 'htmlTagN' },
  rustTypedef                    = { link = 'ErrorMsg' },
  muttrcSetStrAssignment         = { link = 'ErrorMsg' },
  jsFunction                     = { link = 'DiffText' },
  jsImport                       = { link = 'DiffText' },
  jsStorageClass                 = { link = 'DiffText' },
  jsExport                       = { link = 'DiffText' },
  jsGlobalObjects                = { link = 'Directory' },
  jsFuncName                     = { link = 'constructor' },
  jsFrom                         = { fg = colour.royal, bold = true },
  jsParen                        = { link = 'LineNr' },
  jsAsyncKeyword                 = { fg = colour.royal, bold = true },
  jsForAwait                     = { fg = colour.royal, bold = true },
  jsArrowFunction                = { link = 'LineNr' },
  jsReturn                       = { link = 'Return' },
  jsFuncBlock                    = { fg = colour.capri, bold = true },
  jsParens                       = { link = 'LineNr' },
  jsFuncCall                     = { link = 'constructor' },
  jsFuncBraces                   = { link = 'LineNr' },
  jsxTag                         = { fg = colour.metal },
  jsxExpressionBlock             = { fg = colour.slate },
  jsxTagName                     = { link = 'Directory' },
  jsxEqual                       = { link = 'LineNr' },
  jsxOpenPunct                   = { link = 'LineNr' },
  jsxClosePunct                  = { link = 'LineNr' },
  jsxOpenTag                     = { link = 'LineNr' },
  jsxComponentName               = { link = 'Directory' },
  jsxAttrib                      = { link = 'Whitespace' },
  jsxBraces                      = { link = 'LineNr' },
  jsTemplateBraces               = { link = 'DiffDelete' },
  jsFuncParens                   = { link = 'LineNr' },
  jsModuleBraces                 = { link = 'LineNr' },
  jsDestructuringBraces          = { link = 'LineNr' },
  jsObjectBraces                 = { link = 'LineNr' },
  jsObjectShorthandProp          = { link = 'LineNr' },
  jsModuleComma                  = { link = 'LineNr' },
  jsObject                       = { link = 'LineNr' },
  jsBrackets                     = { link = 'LineNr' },
  jsObjectColon                  = { link = 'LineNr' },
  jsNoise                        = { link = 'LineNr' },
  jsFuncArgs                     = { link = 'LineNr' },
  jsFuncArgsCommas               = { link = 'LineNr' },
  jsObjectKey                    = { link = 'Whitespace' },
  jsNull                         = { link = 'gitcommitBranch' },
  jsTernaryIf                    = { link = 'gitcommitBranch' },
  jsTernaryOperator              = { link = 'gitcommitBranch' },
  jsTemplateString               = { link = 'Comment' },
  jsObjectSeparator              = { link = 'LineNr' },
  jsObjectValue                  = { link = 'constructor' },
  jsObjectObjectProp             = { link = 'gitcommitBranch' },
  jsonQuote                      = { fg = colour.royal },
  jsoncBraces                    = { fg = colour.metal },
  jsoncBoolean                   = { fg = colour.mauve },
  CmpCompletionBorder            = { link = 'FloatBorder' },
  CmpItemKindFunction            = { link = 'gitcommitBranch' },
  CmpItemKindMethod              = { link = 'gitcommitBranch' },
  CmpItemKindVariable            = { link = 'DiffAdd' },
  CmpItemKindKeyword             = { link = 'DiffChange' },
  CmpItemKindColor               = { link = 'variable' },
  CmpItemKindConstant            = { link = 'DiffText' },
  CmpItemKindDefault             = { link = 'DiffText' },
  CmpItemKindFolder              = { link = 'Return' },
  CmpItemKindOperator            = { link = 'variable' },
  CmpItemKindProperty            = { link = 'gitcommitBranch' },
  CmpItemMenu                    = { fg = colour.capri, bg = 'none' },
  CmpItemAbbrMatchDefault        = { link = 'gitcommitBranch' },
  CmpItemAbbrMatch               = { link = 'gitcommitBranch' },
  CmpItemAbbrMatchFuzzy          = { link = 'gitcommitBranch' },
  CmpItemKindMatchFuzzy          = { link = 'gitcommitBranch' },
  CmpItemAbbrMatchFuzzyDefault   = { link = 'gitcommitBranch' },
  tsxAttrib                      = { fg = colour.capri },
  tsxCloseString                 = { link = 'LineNr' },
  tsxCloseTag                    = { link = 'LineNr' },
  tsxEqual                       = { link = 'LineNr' },
  tsxRegion                      = { fg = colour.pearl },
  tsxTag                         = { link = 'LineNr' },
  tsxString                      = { link = 'DiffAdd' },
  tsxTagName                     = { fg = colour.steel, bold = true },
  tsxCloseTagName                = { fg = colour.steel, bold = true },
  tsxIntrinsicTagName            = { link = 'htmlTagN' },
  tsxCloseComponentName          = { fg = colour.steel, bold = true },
  txsRegion                      = { link = 'LineNr' },
  typescriptArray                = { fg = colour.pearl },
  typescriptNull                 = { fg = colour.ultra, bold = true },
  typescriptFuncCallArg          = { fg = colour.pearl, bold = true },
  typescriptEnum                 = { link = 'field' },
  typescriptEnumKeyword          = { link = 'DiffText' },
  typescriptArrowFunc            = { link = 'LineNr' },
  typescriptArrowFuncArg         = { link = 'Title' },
  typescriptFuncTypeArrow        = { link = 'LineNr' },
  typescriptFuncComma            = { fg = colour.metal },
  typescriptAssign               = { link = 'LineNr' },
  typescriptAsyncFuncKeyword     = { link = 'Directory' },
  typescriptBOM                  = { link = 'variable' },
  typescriptBOMLocationMethod    = { link = 'DiffText' },
  typescriptBOMWindowProp        = { link = 'DiffAdd' },
  typescriptBlock                = { fg = colour.pearl },
  typescriptBraces               = { link = 'LineNr' },
  typescriptFuncImpl             = { link = 'LineNr' },
  typescriptDOMDocProp           = { link = 'DiffText' },
  typescriptDOMWindowProp        = { link = 'DiffText' },
  typescriptDestructureVariable  = { link = 'variable' },
  typescriptDotNotation          = { link = 'ErrorMsg' },
  typescriptExceptions           = { link = 'DiffText' },
  typescriptExport               = { link = 'htmlTagN' },
  typescriptFuncKeyword          = { link = 'Special' },
  typescriptHeadersMethod        = { link = 'DiffText' },
  typescriptImport               = { link = 'htmlTagN' },
  typescriptObjectColon          = { link = 'LineNr' },
  typescriptObjectLabel          = { link = 'Whitespace' },
  typescriptObjectLiteral        = { link = 'LineNr' },
  tsxEscJs                       = { fg = colour.pearl },
  typescriptTypeAnnotation       = { link = 'LineNr' },
  typescriptOperator             = { fg = colour.bazil, bold = true },
  typescriptParens               = { link = 'LineNr' },
  typescriptParenExp             = { fg = colour.pearl },
  typescriptProp                 = { fg = colour.capri },
  typescriptArrayMethod          = { fg = colour.royal, bold = true },
  typescriptProperty             = { link = 'LineNr' },
  typescriptResponseProp         = { link = 'DiffText' },
  typescriptStatementKeyword     = { link = 'Return' },
  typescriptStringMethod         = { link = 'DiffText' },
  typescriptTemplate             = { fg = colour.slate, italic = true },
  typescriptTemplateSubstitution = { fg = colour.capri, italic = true },
  typescriptTemplateSB           = { link = 'DiffText' },
  typescriptTernary              = { link = 'Return' },
  typescriptTernaryOp            = { fg = colour.amber },
  typescriptTry                  = { link = 'Directory' },
  typescriptTypeBrackets         = { link = 'LineNr' },
  typescriptUnaryOp              = { fg = colour.amber },
  typescriptBinaryOp             = { fg = colour.amber },
  typescriptVariable             = { link = 'DiffText' },
  typescriptXHRMethod            = { link = 'DiffText' },
  typescriptTypeReference        = { fg = colour.bazil, bold = true },
  typescriptTypeCase             = { fg = colour.royal },
  typescriptIdentifierName       = { fg = colour.pearl },
  muttrcAliasEncEmail            = { fg = colour.metal },
  muttrcEmail                    = { fg = colour.bazil },
  markdownValid                  = { fg = colour.metal, bold = true, italic = true },
  muttrcAliasKey                 = { fg = colour.mauve, bold = true },
  muttrcAliasNameNoParens        = { fg = colour.pearl, bold = true },
  mailHeader                     = { fg = colour.rouge },
  mailHeaderKey                  = { fg = colour.rouge },
  WhichKey                       = { fg = colour.rouge, bold = true },
  WhichKeyGroup                  = { fg = colour.royal, bold = true },
  WhichKeySeparator              = { fg = colour.royal, bold = true },
}

for group, styles in pairs(lang_syntax) do
  highlight(tostring(group), styles)
end
