local colour = require 'synful.colour'

return {
  Boolean                        = { fg = colour.mauve },
  Builtin                        = { fg = colour.pearl },
  Character                      = { link = 'constructor' },
  CmpCompletionBorder            = { link = 'FloatBorder' },
  CmpItemAbbrMatch               = { link = 'gitcommitBranch' },
  CmpItemAbbrMatchDefault        = { link = 'gitcommitBranch' },
  CmpItemAbbrMatchFuzzy          = { link = 'gitcommitBranch' },
  CmpItemAbbrMatchFuzzyDefault   = { link = 'gitcommitBranch' },
  CmpItemKindColor               = { link = 'variable' },
  CmpItemKindConstant            = { link = 'DiffText' },
  CmpItemKindDefault             = { link = 'DiffText' },
  CmpItemKindFolder              = { link = 'Return' },
  CmpItemKindFunction            = { link = 'gitcommitBranch' },
  CmpItemKindKeyword             = { link = 'DiffChange' },
  CmpItemKindMatchFuzzy          = { link = 'gitcommitBranch' },
  CmpItemKindMethod              = { link = 'gitcommitBranch' },
  CmpItemKindOperator            = { link = 'variable' },
  CmpItemKindProperty            = { link = 'gitcommitBranch' },
  CmpItemKindVariable            = { link = 'DiffAdd' },
  CmpItemMenu                    = { link = 'CmpItemMenu' },
  ColorColumn                    = { fg = "NONE", bg = "NONE" },
  Command                        = { link = 'DiffText' },
  Comment                        = { fg = colour.metal, bold = true, italic = true },
  Conditional                    = { link = 'Conditional' },
  Constant                       = { link = 'DiffText' },
  Cursor                         = { fg = colour.pearl, bg = colour.rouge },
  CursorLine                     = { bg = colour.raven },
  CursorLineNr                   = { fg = colour.capri, bg = colour.raven },
  Debug                          = { link = 'DiffDelete' },
  Define                         = { link = 'DiffText' },
  Delimiter                      = { link = 'LineNr' },
  DiagnosticError                = { fg = colour.rouge, bold = true },
  DiagnosticHint                 = { fg = colour.peach, bold = true },
  DiagnosticInfo                 = { link = 'CmpItemMenu' },
  DiagnosticUnderlineError       = { fg = colour.rouge, bold = true },
  DiagnosticUnderlineHint        = { link = 'DiagnosticUnderlineHint' },
  DiagnosticUnderlineInfo        = { link = 'CmpItemMenu' },
  DiagnosticUnderlineWarn        = { fg = colour.amber },
  DiagnosticVirtualTextError     = { fg = colour.rouge, bold = true },
  DiagnosticVirtualTextHint      = { link = 'DiagnosticUnderlineHint' },
  DiagnosticVirtualTextInfo      = { link = 'CmpItemMenu' },
  DiagnosticVirtualTextWarn      = { fg = colour.amber },
  DiagnosticWarn                 = { fg = colour.amber },
  DiffAdd                        = { fg = colour.paris },
  DiffChange                     = { fg = colour.metal },
  DiffDelete                     = { fg = colour.rouge },
  DiffText                       = { link = 'Conditional' },
  Directory                      = { fg = colour.steel, bold = true },
  EndOfBuffer                    = { fg = colour.space, bg = colour.space },
  Error                          = { fg = colour.rouge },
  ErrorMsg                       = { link = 'Error' },
  Exception                      = { fg = colour.royal, bold = true },
  FidgetTitle                    = { fg = colour.capri, bg = colour.space },
  Field                          = { link = 'variable' },
  Float                          = { link = 'gitcommitBranch' },
  FloatBorder                    = { fg = colour.raven },
  FloatShadow                    = { bg = "NONE" },
  FloatShadowThrough             = { bg = "NONE" },
  FoldColumn                     = { link = 'Boolean' },
  Folded                         = { link = 'Boolean' },
  Function                       = { link = 'constructor' },
  GitGutterAdd                   = { link = 'gitcommitUnmerged' },
  GitGutterChange                = { link = 'LineNr' },
  GitGutterChangeDelete          = { fg = colour.amber },
  GitGutterDelete                = { link = 'DiffDelete' },
  Identifier                     = { link = 'variable' },
  Ignore                         = { link = 'DiffChange' },
  IncSearch                      = { fg = colour.ultra, bg = colour.royal, bold = true },
  Include                        = { fg = colour.royal, bold = true },
  KeywordFunction                = { link = 'DiffText' },
  KeywordReturn                  = { fg = colour.olive, italic = true },
  Label                          = { link = 'DiffText' },
  LineNr                         = { fg = colour.metal },
  Macro                          = { link = 'Conditional' },
  MatchParen                     = { fg = colour.rouge, bold = true },
  Noise                          = { fg = colour.rouge },
  Normal                         = { fg = colour.pearl, bg = colour.space },
  NormalFloat                    = { bg = colour.space },
  NotifyDEBUGBody                = { link = 'Normal' },
  NotifyDEBUGBorder              = { fg = colour.slate },
  NotifyDEBUGIcon                = { fg = colour.slate },
  NotifyDEBUGTitle               = { fg = colour.slate },
  NotifyERRORBody                = { link = 'Normal' },
  NotifyERRORBorder              = { link = 'ErrorMsg' },
  NotifyERRORIcon                = { link = 'DiffDelete' },
  NotifyERRORTitle               = { link = 'DiffDelete' },
  NotifyINFOBody                 = { link = 'Normal' },
  NotifyINFOBorder               = { fg = colour.bazil },
  NotifyINFOIcon                 = { link = 'DiffAdd' },
  NotifyINFOTitle                = { link = 'DiffAdd' },
  NotifyTRACEBody                = { link = 'Normal' },
  NotifyTRACEBorder              = { link = 'Boolean' },
  NotifyTRACEIcon                = { link = 'gitcommitNoBranch' },
  NotifyTRACETitle               = { link = 'gitcommitNoBranch' },
  NotifyWARNBody                 = { link = 'Normal' },
  NotifyWARNBorder               = { link = 'FoldColumn' },
  NotifyWARNIcon                 = { link = 'Tag' },
  NotifyWARNTitle                = { link = 'Tag' },
  Number                         = { fg = colour.ultra, bold = true },
  NvimInternalError              = { link = 'ErrorMsg' },
  Operator                       = { link = 'DiagnosticUnderlineHint' },
  Pmenu                          = { fg = colour.pearl, bg = colour.space },
  PmenuSbar                      = { link = 'Builtin' },
  PmenuSel                       = { fg = colour.capri, bg = colour.raven, bold = true },
  PmenuThumb                     = { fg = colour.rouge, bg = colour.rouge },
  PreCondit                      = { link = 'DiffChange' },
  PreProc                        = { fg = colour.slate },
  Repeat                         = { link = 'Return' },
  Return                         = { fg = colour.bazil, bold = true },
  Search                         = { fg = colour.pearl, bg = colour.royal },
  SignColumn                     = { link = 'DiagnosticUnderlineHint' },
  Special                        = { link = 'Conditional' },
  SpecialChar                    = { link = 'ErrorMsg' },
  SpecialComment                 = { fg = colour.metal, bold = true },
  SpecialKey                     = { link = 'Conditional' },
  SpellBad                       = { fg = colour.rouge, bold = true },
  SpellCap                       = { link = 'DiagnosticHint' },
  SpellLocal                     = { fg = colour.amber, bold = true },
  SpellRare                      = { fg = colour.royal, bold = true },
  Statement                      = { fg = colour.royal, bold = true },
  StorageClass                   = { fg = colour.rouge },
  String                         = { fg = colour.paris, italic = true },
  Structure                      = { link = 'Builtin' },
  Substitute                     = { fg = colour.pearl, bg = colour.rouge },
  TabLine                        = { fg = colour.pearl, bg = colour.rouge },
  TabLineFill                    = { fg = colour.pearl, bg = colour.metal },
  TabLineSel                     = { fg = colour.space, bg = colour.raven, bold = true },
  Tag                            = { fg = colour.amber },
  TelescopeBorder                = { link = 'FloatBorder' },
  TelescopeMatching              = { fg = colour.ultra, bold = true },
  TelescopePreviewMatch          = { link = 'MatchParen' },
  TelescopePromptPrefix          = { fg = colour.rouge },
  TelescopePromptTitle           = { link = 'Conditional' },
  TelescopeSelection             = { link = 'PmenuSel' },
  TelescopeSelectionCaret        = { fg = colour.rouge, bg = colour.raven, bold = true },
  Title                          = { link = 'Builtin' },
  Todo                           = { fg = colour.capri, bold = true },
  Type                           = { fg = colour.paris, bold = true },
  Typedef                        = { link = 'DiffChange' },
  Underlined                     = { underline = true },
  VertSplit                      = { fg = colour.metal, bg = colour.space },
  Visual                         = { fg = colour.pearl, bg = colour.royal },
  VisualNOS                      = { fg = colour.pearl, bg = colour.rouge },
  WarningMsg                     = { link = 'DiagnosticUnderlineHint' },
  WhichKey                       = { fg = colour.rouge, bold = true },
  WhichKeyGroup                  = { fg = colour.royal, bold = true },
  WhichKeySeparator              = { fg = colour.royal, bold = true },
  Whitespace                     = { link = 'CmpItemMenu' },
  WildMenu                       = {},
  constructor                    = { fg = colour.pearl, bold = true },
  diffAdded                      = { link = 'gitcommitUnmerged' },
  diffRemoved                    = { link = 'DiffDelete' },
  field                          = { link = 'Builtin' },
  gitcommitBranch                = { fg = colour.ultra, bold = true },
  gitcommitComment               = { fg = colour.metal },
  gitcommitDiscarded             = { fg = colour.metal },
  gitcommitDiscardedArrow        = { fg = colour.rouge },
  gitcommitDiscardedFile         = { fg = colour.rouge },
  gitcommitDiscardedType         = { fg = colour.rouge },
  gitcommitNoBranch              = { fg = colour.ultra },
  gitcommitOverflow              = { fg = colour.rouge },
  gitcommitSelected              = { fg = colour.metal },
  gitcommitSelectedArrow         = { fg = colour.olive },
  gitcommitSelectedFile          = { fg = colour.olive },
  gitcommitSelectedType          = { fg = colour.olive },
  gitcommitSummary               = { link = 'Builtin' },
  gitcommitUnmerged              = { fg = colour.olive },
  gitcommitUnmergedArrow         = { link = 'DiagnosticUnderlineHint' },
  gitcommitUnmergedFile          = { link = 'DiagnosticUnderlineHint' },
  gitcommitUntracked             = { fg = colour.metal },
  gitcommitUntrackedFile         = { link = 'Conditional' },
  htmlArg                        = { link = 'LineNr' },
  htmlEndTag                     = { link = 'LineNr' },
  htmlHead                       = { link = 'DiffText' },
  htmlSpecialTagName             = { link = 'Conditional' },
  htmlTag                        = { link = 'LineNr' },
  htmlTagN                       = { fg = colour.royal, bold = true },
  htmlTagName                    = { fg = colour.royal, bold = true },
  jsArrowFunction                = { link = 'LineNr' },
  jsAsyncKeyword                 = { fg = colour.royal, bold = true },
  jsBrackets                     = { link = 'LineNr' },
  jsDestructuringBraces          = { link = 'LineNr' },
  jsExport                       = { link = 'DiffText' },
  jsForAwait                     = { fg = colour.royal, bold = true },
  jsFrom                         = { fg = colour.royal, bold = true },
  jsFuncArgs                     = { link = 'LineNr' },
  jsFuncArgsCommas               = { link = 'LineNr' },
  jsFuncBlock                    = { fg = colour.capri, bold = true },
  jsFuncBraces                   = { link = 'LineNr' },
  jsFuncCall                     = { link = 'constructor' },
  jsFuncName                     = { link = 'constructor' },
  jsFuncParens                   = { link = 'LineNr' },
  jsFunction                     = { link = 'DiffText' },
  jsGlobalObjects                = { link = 'Directory' },
  jsImport                       = { link = 'DiffText' },
  jsModuleBraces                 = { link = 'LineNr' },
  jsModuleComma                  = { link = 'LineNr' },
  jsNoise                        = { link = 'LineNr' },
  jsNull                         = { link = 'gitcommitBranch' },
  jsObject                       = { link = 'LineNr' },
  jsObjectBraces                 = { link = 'LineNr' },
  jsObjectColon                  = { link = 'LineNr' },
  jsObjectKey                    = { link = 'Whitespace' },
  jsObjectObjectProp             = { link = 'gitcommitBranch' },
  jsObjectSeparator              = { link = 'LineNr' },
  jsObjectShorthandProp          = { link = 'LineNr' },
  jsObjectValue                  = { link = 'constructor' },
  jsParen                        = { link = 'LineNr' },
  jsParens                       = { link = 'LineNr' },
  jsReturn                       = { link = 'Return' },
  jsStorageClass                 = { link = 'DiffText' },
  jsTemplateBraces               = { link = 'DiffDelete' },
  jsTemplateString               = { link = 'Comment' },
  jsTernaryIf                    = { link = 'gitcommitBranch' },
  jsTernaryOperator              = { link = 'gitcommitBranch' },
  jsonQuote                      = { link = 'Conditional' },
  jsoncBoolean                   = { link = 'Boolean' },
  jsoncBraces                    = { fg = colour.metal },
  jsxAttrib                      = { link = 'Whitespace' },
  jsxBraces                      = { link = 'LineNr' },
  jsxClosePunct                  = { link = 'LineNr' },
  jsxComponentName               = { link = 'Directory' },
  jsxEqual                       = { link = 'LineNr' },
  jsxExpressionBlock             = { fg = colour.slate },
  jsxOpenPunct                   = { link = 'LineNr' },
  jsxOpenTag                     = { link = 'LineNr' },
  jsxTag                         = { fg = colour.metal },
  jsxTagName                     = { link = 'Directory' },
  keyword                        = { link = 'Directory' },
  luaBraces                      = { link = 'LineNr' },
  luaBuiltIn                     = { link = 'DiffText' },
  luaComma                       = { link = 'LineNr' },
  luaConstant                    = { link = 'gitcommitBranch' },
  luaFunc                        = { link = 'DiffText' },
  luaFuncArgsComma               = { link = 'LineNr' },
  luaFuncCall                    = { link = 'Directory' },
  luaFuncName                    = { link = 'constructor' },
  luaFuncParens                  = { link = 'LineNr' },
  luaFunction                    = { link = 'Conditional' },
  luaFunctionBlock               = { fg = colour.royal, bold = true },
  luaIn                          = { fg = colour.royal, bold = true },
  luaKeyword                     = { link = 'Return' },
  luaLocal                       = { fg = colour.olive, bold = true },
  luaParen                       = { link = 'LineNr' },
  luaParens                      = { link = 'LineNr' },
  luaSpecialValue                = { link = 'Directory' },
  luaStatement                   = { link = 'Return' },
  luaString                      = { link = 'String' },
  luaStringLongTag               = { fg = colour.metal, bold = true },
  luaSymbolOperator              = { link = 'LineNr' },
  luaTable                       = { link = 'LineNr' },
  luaTableBlock                  = { link = 'LineNr' },
  mailHeader                     = { fg = colour.rouge },
  mailHeaderKey                  = { fg = colour.rouge },
  markdownValid                  = { fg = colour.metal, bold = true, italic = true },
  mkdNonListItemBlock            = { link = 'Folded' },
  muttrcAliasEncEmail            = { fg = colour.metal },
  muttrcAliasKey                 = { link = 'Boolean' },
  muttrcAliasNameNoParens        = { fg = colour.pearl, bold = true },
  muttrcEmail                    = { fg = colour.bazil },
  muttrcSetStrAssignment         = { link = 'ErrorMsg' },
  rustAssert                     = { link = 'ErrorMsg' },
  rustBoxPlacementBalance        = { link = 'ErrorMsg' },
  rustCharacter                  = { link = 'ErrorMsg' },
  rustConditional                = { link = 'Directory' },
  rustEnumVariant                = { link = 'field' },
  rustFoldBraces                 = { link = 'LineNr' },
  rustFuncCall                   = { link = 'field' },
  rustFuncName                   = { link = 'constructor' },
  rustIdentifier                 = { link = 'variable' },
  rustKeyword                    = { link = 'Directory' },
  rustMacro                      = { link = 'Return' },
  rustModPath                    = { link = 'Return' },
  rustModPathSep                 = { link = 'LineNr' },
  rustOperator                   = { link = 'LineNr' },
  rustRepeat                     = { link = 'Directory' },
  rustSelf                       = { link = 'ErrorMsg' },
  rustSigil                      = { link = 'ErrorMsg' },
  rustStorage                    = { link = 'Directory' },
  rustStructure                  = { link = 'Return' },
  rustTrait                      = { link = 'htmlTagN' },
  rustTypedef                    = { link = 'ErrorMsg' },
  shDerefSimple                  = { fg = colour.amber },
  shDo                           = { link = 'ErrorMsg' },
  shDoubleQuote                  = { fg = colour.amber },
  shEcho                         = { fg = colour.paris, italic = true },
  shQuote                        = { fg = colour.amber },
  shStatement                    = { link = 'htmlTagN' },
  shTestOpr                      = { link = 'ErrorMsg' },
  shVar                          = { link = 'CmpItemMenu' },
  shVarAssign                    = { link = 'LineNr' },
  tmuxAssignment                 = { link = 'LineNr' },
  tmuxFlags                      = { link = 'ErrorMsg' },
  tmuxFormatString               = { link = 'CmpItemMenu' },
  tmuxOptions                    = { link = 'variable' },
  tmuxVariableExtension          = { fg = colour.amber },
  tsxAttrib                      = { link = 'CmpItemMenu' },
  tsxCloseComponentName          = { fg = colour.steel, bold = true },
  tsxCloseString                 = { link = 'LineNr' },
  tsxCloseTag                    = { link = 'LineNr' },
  tsxCloseTagName                = { fg = colour.steel, bold = true },
  tsxEqual                       = { link = 'LineNr' },
  tsxEscJs                       = { link = 'Builtin' },
  tsxIntrinsicTagName            = { link = 'htmlTagN' },
  tsxRegion                      = { link = 'Builtin' },
  tsxString                      = { link = 'DiffAdd' },
  tsxTag                         = { link = 'LineNr' },
  tsxTagName                     = { fg = colour.steel, bold = true },
  txsRegion                      = { link = 'LineNr' },
  typescriptArray                = { link = 'Builtin' },
  typescriptArrayMethod          = { fg = colour.royal, bold = true },
  typescriptArrowFunc            = { link = 'LineNr' },
  typescriptArrowFuncArg         = { link = 'Title' },
  typescriptAssign               = { link = 'LineNr' },
  typescriptAsyncFuncKeyword     = { link = 'Directory' },
  typescriptBOM                  = { link = 'variable' },
  typescriptBOMLocationMethod    = { link = 'DiffText' },
  typescriptBOMWindowProp        = { link = 'DiffAdd' },
  typescriptBinaryOp             = { fg = colour.amber },
  typescriptBlock                = { link = 'Builtin' },
  typescriptBraces               = { link = 'LineNr' },
  typescriptDOMDocProp           = { link = 'DiffText' },
  typescriptDOMWindowProp        = { link = 'DiffText' },
  typescriptDestructureVariable  = { link = 'variable' },
  typescriptDotNotation          = { link = 'ErrorMsg' },
  typescriptEnum                 = { link = 'field' },
  typescriptEnumKeyword          = { link = 'DiffText' },
  typescriptExceptions           = { link = 'DiffText' },
  typescriptExport               = { link = 'htmlTagN' },
  typescriptFuncCallArg          = { link = 'Builtin' },
  typescriptFuncComma            = { fg = colour.metal },
  typescriptFuncImpl             = { link = 'LineNr' },
  typescriptFuncKeyword          = { link = 'Special' },
  typescriptFuncTypeArrow        = { link = 'LineNr' },
  typescriptHeadersMethod        = { link = 'DiffText' },
  typescriptIdentifierName       = { link = 'Builtin' },
  typescriptImport               = { link = 'htmlTagN' },
  typescriptNull                 = { fg = colour.ultra, bold = true },
  typescriptObjectColon          = { link = 'LineNr' },
  typescriptObjectLabel          = { link = 'Whitespace' },
  typescriptObjectLiteral        = { link = 'LineNr' },
  typescriptOperator             = { fg = colour.bazil, bold = true },
  typescriptParenExp             = { link = 'Builtin' },
  typescriptParens               = { link = 'LineNr' },
  typescriptProp                 = { link = 'CmpItemMenu' },
  typescriptProperty             = { link = 'LineNr' },
  typescriptResponseProp         = { link = 'DiffText' },
  typescriptStatementKeyword     = { link = 'Return' },
  typescriptStringMethod         = { link = 'DiffText' },
  typescriptTemplate             = { fg = colour.slate, italic = true },
  typescriptTemplateSB           = { link = 'DiffText' },
  typescriptTemplateSubstitution = { link = 'CmpItemMenu', italic = true },
  typescriptTernary              = { link = 'Return' },
  typescriptTernaryOp            = { fg = colour.amber },
  typescriptTry                  = { link = 'Directory' },
  typescriptTypeAnnotation       = { link = 'LineNr' },
  typescriptTypeBrackets         = { link = 'LineNr' },
  typescriptTypeCase             = { link = 'Conditional' },
  typescriptTypeReference        = { fg = colour.bazil, bold = true },
  typescriptUnaryOp              = { fg = colour.amber },
  typescriptVariable             = { link = 'DiffText' },
  typescriptXHRMethod            = { link = 'DiffText' },
  variable                       = { link = 'Builtin' },
  xmlEndTag                      = { fg = colour.royal, bold = true },
  zshCommands                    = { link = 'DiffText' },
  zshDeref                       = { link = 'Whitespace' },
  zshFunction                    = { link = 'WarningMsg' },
  zshKeyword                     = { link = 'Function' },
  zshNumber                      = { link = 'Number' },
  zshOptStart                    = { fg = colour.royal, bold = true },
  zshOption                      = { fg = colour.royal, bold = true },
  zshParentheses                 = { link = 'Boolean' },
  zshPreProc                     = { link = 'PreProc' },
  zshPrecommand                  = { link = 'DiffText' },
  zshString                      = { link = 'String' },
  zshStringDelimiter             = { link = 'String' },
  zshSubst                       = { link = 'DiffChange' },
  zshSubstDelim                  = { fg = colour.amber },
  zshTodo                        = { link = 'Todo' },
  zslhComment                    = { link = 'Comment' },
}
