vim.cmd("syntax match txtComment '--.*'")
vim.cmd("syntax match txtString '\".*\"'")
vim.cmd("syntax match txtBoolean 'true'")
vim.cmd("syntax match txtBoolean 'false'")
vim.cmd("syntax match txtNumber '\\d\\+\\(\\.\\d\\+\\)?'")
vim.cmd("syntax match txtTodo '\\(TODO\\|NOTE\\|FIXME\\)'")
vim.cmd('syntax region txtString start=+"+ end=+"+')
vim.cmd("hi def link txtComment Comment")
vim.cmd("hi def link txtString String")
vim.cmd("hi def link txtBoolean Boolean")
vim.cmd("hi def link txtNumber Number")
vim.cmd("hi def link txtTodo Todo")
